doc-warnings: false
test-warnings: false
strictness: medium
max-line-length: 120
uses:
  - django
autodetect: true
ignore-patterns:
  - ^tests/test_.*\.py$
  - (^|/)migrations(/|$)
python-targets:
  - 2
  - 3
