sudo: required
language: python
services:
  - docker

before_install:
  - docker run -d --name ispa_db -e "POSTGRES_USER=postgres" -e "POSTGRES_PASSWORD=postgres" -e "POSTGRES_DB=postgres" postgres:9.5.3
install:
  - cd ispa
  - docker build -f Dockerfile.local -t $REPO:$TRAVIS_COMMIT .
script:
  - docker run --name ispa --link ispa_db --entrypoint /bin/bash $REPO:$TRAVIS_COMMIT -c py.test
  - docker ps | grep -q ispa
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

notifications:
  email:
    recipients:
      - aleccunningham96@gmail.com
      #- freddymrqz28@gmail.com
    on_success: never
    on_failure: always
