sudo: required
language: python

services:
  - docker
addons:
    hosts:
        - db

before_install:
  - pip install coveralls

install:
  - docker build -f ispa/Dockerfile.local -t $REPO:$TRAVIS_COMMIT ./ispa

script:
  - docker run -it --rm --volume $(pwd)/.coverage:/home/docker/ispa/.coverage --name ispa --entrypoint /bin/bash $REPO:$TRAVIS_COMMIT -c py.test --cov --pep8
  - coveralls
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT-$DEV
  - docker push $REPO

notifications:
  email:
    recipients:
      - aleccunningham96@gmail.com
      #- freddymrqz28@gmail.com
    on_success: never
    on_failure: always
