sudo: required
language: python

services:
  - docker
addons:
    hosts:
        - db

install:
  - docker build -f Dockerfile.local -t ispa_local:latest .

script:
  - echo "Built"

notifications:
  email:
    recipients:
      - aleccunningham96@gmail.com
      - freddymrqz28@gmail.com
    on_success: never
    on_failure: always
