sudo: required

services:
  - docker

before_install:
  - docker run -d --name postgres -e "POSTGRES_USER=user" -e "POSTGRES_PASSWORD=postgres" -e "POSTGRES_DB=postgres" postgres:9.5.3

install:
  - cd ispa
  - docker build -t ispa:latest-local -f Dockerfile.local .
  - docker run --name ispa --link postgres ispa:latest-local

script:
  - docker ps | grep -q ispa
