sudo: required
language: python

addons:
  postgresql: "9.4"

services:
  - docker
  - postgresql

install:
  - cd ispa
  - docker build -t ispa:latest-local -f Dockerfile.local .
  - docker run --name ispa ispa:latest-local

script:
  - docker ps | grep -q ispa
