sudo: required

cache:
  directories:
  - $CACHE_DIR

before_install:
  - if [ -f ${CACHE_FILE_NODE} ]; then gunzip -c ${CACHE_FILE_NODE} | docker load; fi

services:
  - docker

before_install:
  - docker run -d --name ispa_db -e "POSTGRES_USER=postgres" -e "POSTGRES_PASSWORD=postgres" -e "POSTGRES_DB=postgres" postgres:9.5.3

install:
  - cd ispa
  - docker build -f Dockerfile.local  -t $REPO:$TRAVIS_COMMIT .
  - docker run --name ispa --link ispa_db $IMAGE_NAME:latest /bin/echo Success

script:
  - docker ps | grep -q ispa

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
