version: '2'

volumes:
    ispa_pg_data:
        external: true
    redisdata:

services:
  db:
    image: postgres:9.4
    container_name: ispa_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOSTNAME=ispa_db
    ports:
      - "5432:5432"
    volumes:
      - ispa_pg_data:/var/lib/postgresql/data

  redis:
      container_name: redis
      image: redis:3.2.0
      ports:
        - '127.0.0.1:6379:6379'
      volumes:
        - 'redisdata:/data'
