version: '2'

services:
  db:
    image: postgres:9.4
    container_name: ispa_db_prod
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    build:
      context: nginx/
    container_name: ispa_nginx_prod
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"

  # Redis
  redis:
    image: redis:3.0
    container_name: ispa_redis_prod


  # RabbitMQ
  rabbit:
    image: rabbitmq:3.6.0
    container_name: ispa_rabbit_prod
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
