version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      labels:
        com.ispa.description: "ISPA webapp"
        com.ispa.maintainer: "Alec Cunningham"
    hostname: web
    volumes:
      - .:/home/docker  # mount current directory inside container
    ports:
      - "8000"
    # set up links so that web knows about db, rabbit and redis
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_celery.sh
    volumes:
      - .:/home/docker
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - rabbit
