version: '2'

volumes:
    ispa_pg_data:
        external: true

services:
  db:
    image: postgres:9.4
    container_name: ispa_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOSTNAME=ispa_db
    ports:
      - "5432:5432"
    volumes:
      - ispa_pg_data:/var/lib/postgresql/data
