version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  db:
    image: postgresql:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"

  django:
    build:
      context: ispa_project/
      dockerfile: Dockerfile
    hostname: django
    command: /gunicorn.sh
    depends_on:
      - db
    env_file: .env

  # Redis
  redis:
    image: redis:3.0
    hostname: redis

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
