version: '2'

volumes:
    ispa_pg_data:
        external: true

services:
  ispa_local:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: ispa_local
    volumes:
      - ./ispa:/home/docker/ispa
    working_dir: /home/docker/ispa
    ports:
      - "8000:8000"
    networks:
      ispa:
    hostname: ispa
    command: /home/docker/bin/start_dev.sh
  celery:
    image: aleccunningham/ispa_local:latest
    container_name: celery_worker
    volumes:
      - ./ispa:/home/docker/ispa
    working_dir: /home/docker/ispa
    networks:
      ispa:
    command: /home/docker/bin/start_celery.sh
  db:
    image: postgres:9.4
    container_name: postgresql
    volumes:
      - ispa_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      ispa:
        aliases:
          - ispa_db
    hostname: postgresql
  redis:
      image: redis:latest
      container_name: redis
      networks:
        ispa:
          aliases:
            - redis
      hostname: redis
      ports:
       - "6379:6379"
networks:
  ispa:
