<<<<<<< HEAD:docker-compose.local.yml
version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  db:
    build:
      context: postgres/
    container_name: ispa_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  django:
    build:
      context: ispa/
      dockerfile: Dockerfile.local
    container_name: ispa
    environment:
      - USE_DOCKER=yes
    volumes:
      - .:/home/docker  # mount current directory inside container
    ports:
      - "8000:8000"
    depends_on:
      - db

  # Redis
  redis:
    image: redis:3.0
    container_name: ispa_redis

  # RabbitMQ
  rabbit:
    container_name: ispa_rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
=======
version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  db:
    build:
      context: postgres/
    container_name: ispa_db_prod
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups

  nginx:
    build:
      context: nginx/
    container_name: ispa_nginx_prod
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"

  django:
    build:
      context: ispa/
      dockerfile: Dockerfile
    container_name: ispa_prod
    depends_on:
      - db
    env_file: .env

  # Redis
  redis:
    image: redis:3.0
    container_name: ispa_redis_prod


  # RabbitMQ
  rabbit:
    image: rabbitmq:3.6.0
    container_name: ispa_rabbit_prod
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
>>>>>>> 545c833f37e5ce15bfa5d5fc2a01af6a04b9635f:docker-compose.prod.yml
