version: '2'

volumes:
    ispa_pg_data:
        external: true

services:
  ispa_local:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: ispa_local
    volumes:
      - ./ispa:/home/docker/ispa
    working_dir: /home/docker/ispa
    ports:
      - "8000:8000"
    networks:
      ispa:
    hostname: ispa
    command: ./start-dev.sh
  celery:
    image: aleccunningham/ispa_local:latest
    container_name: celery_worker
    working_dir: /home/docker/ispa
    networks:
      ispa:
    command: ./start-celery.sh
  db:
    image: postgres:9.4
    container_name: postgresql
    volumes:
      - ispa_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      ispa:
        aliases:
          - ispa_db
    hostname: postgresql
  rabbit:
    image: rabbitmq:3.6.2
    container_name: rabbitmq
    networks:
      ispa:
        aliases:
          - rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=isba
      - RABBITMQ_DEFAULT_PASS=justtestit
      - RABBITMQ_DEFAULT_VHOST=ispa_host

networks:
  ispa:
