version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  nginx:
    build:
      context: .
      dockerfile: ispa_project/nging/Dockerfile
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"

  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
      labels:
        com.ispa.description: "ISPA webapp"
        com.ispa.maintainer: "Alec Cunningham"
    hostname: web
    command: /gunicorn.sh
    depends_on:
      - db
    env_file: .env

  # Redis
  redis:
    image: redis:3.0
    hostname: redis

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_celery.sh
    volumes:
      - .:/home/docker
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - rabbit
