version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  db:
    build:
      context: postgres/
    container_name: ispa_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  django:
    build:
      context: ispa/
      dockerfile: Dockerfile.local
    container_name: ispa
    environment:
      - USE_DOCKER=yes
    volumes:
      - .:/home/docker  # mount current directory inside container
    ports:
      - "8000:8000"
    depends_on:
      - db

  # Redis
  redis:
    image: redis:3.0
    container_name: ispa_redis

  # RabbitMQ
  rabbit:
    container_name: ispa_rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
