version: '2'

volumes:
    ispa_pg_data:
        external: true
    redisdata:

services:
  ispa_local:
    container_name: ispa_local
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./ispa:/home/docker/ispa
    ports:
      - "8000:8000"
    command: /start-dev.sh

  celery:
    container_name: celery_worker
    image: ispa_local
    command: /start-celery.sh

  db:
    image: postgres:9.4
    container_name: ispa_db
    ports:
      - "5432:5432"
    volumes:
      - ispa_pg_data:/var/lib/postgresql/data

  redis:
      container_name: redis
      image: redis:3.2.0
      ports:
        - "6379:6379"
      volumes:
        - redisdata:/data
